on: push

jobs:
    aliAction:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Cache node modules
              uses: actions/cache@v2
              env:
                  cache-name: cache-node-modules
              with:
                  # npm cache files are stored in `~/.npm` on Linux/macOS
                  path: ~/.npm
                  key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-build-${{ env.cache-name }}-
                      ${{ runner.os }}-build-
                      ${{ runner.os }}-

            - name: Install
              run: npm install

            - name: get scope
              run: node scripts/getscope.js

            - name: Deploy to aliyun server
              uses: easingthemes/ssh-deploy@v2.1.5
              if: ${{success()}}
              env:
                  SSH_PRIVATE_KEY: ${{ secrets.ALIYUN_SERVER_ACCESS_TOKEN }}
                  ARGS: '-avz --delete'
                  SOURCE: 'projects/${{env.SCOPE}}/${{env.SCOPE}}'
                  REMOTE_HOST: ${{ secrets.ALIYUN_SERVER_HOST }}
                  REMOTE_USER: 'root'
                  TARGET: '/usr/share/nginx/html'
