name: Hexo build and deploy

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
      with:
        persist-credentials: false
        # checkout到你的hexo代码分支
        # ref: dev
        # hexo需要加载内部子模块
        submodules: true
    - name: Install and Build
      run: |
        npm install
        npm run build
        mv public/ blog/
    # - name: Prepare SSH
    #   run: >
    #     cd ~ && mkdir .ssh &&
    #     touch ~/.ssh/known_hosts &&
    #     ssh-keyscan -H "$IP" >>~/.ssh/known_hosts
    #   env:
    #     IP: ${{ secrets.ALIYUN_SERVER_HOST }}
    - name: Deploy to aliyun server
      uses: easingthemes/ssh-deploy@v2.1.5
      env:
        SSH_PRIVATE_KEY: ${{ secrets.ALIYUN_SERVER_ACCESS_TOKEN }}
        ARGS: "-avz --delete"
        SOURCE: "blog"
        REMOTE_HOST: ${{ secrets.ALIYUN_SERVER_HOST }}
        REMOTE_USER: "root"
        TARGET: "/usr/share/nginx/html"